name: Build

on:
  push

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Make gradlew executable
        run: chmod +x gradlew 

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Build application
        run: ./gradlew :rust:run --args="example/helloworld.rs --dump-tokens"

      - name: Run test application
        run: ./gradlew :rust:test
